import { Figtree, Permanent_Marker } from "next/font/google";

import "./globals.css";

import Header from "@/components/Header";

export const figTree = Figtree({ subsets: ["latin"], display: "swap", weight: ["400"], variable: "--font-figtree" });
export const pMarker = Permanent_Marker({ subsets: ["latin"], display: "swap", weight: ["400"], variable: "--font-permanent-marker" });
// import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-100 px-10 ${figTree.variable} ${pMarker.variable}`}>
        <main className="mx-auto figTeeFont">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
